# This is a program for smoothing the spectrum graphics using Savitzky–Golay filter.
# It uses spectrum.xlsx, a file generated by HYPER-S.py as both input and output.

import numpy as np
import pandas as pd
from scipy.signal import savgol_filter
from xlsxwriter import Workbook

input_file = 'spectrum.xlsx'
output_file = input_file

# Set the window size and polynomial order
window_size = 10
poly_order = 3

print('This program applies Savitzky–Golay filter to the means of the reflectance spectra\n'
      'located in a file <spectrum.xlsx> produced by <spectrum.py> program.\n'
      'The output will be done to the same file on a new sheet named <Means-SavGol>.\n'
      'Please, make a copy of initial file for its safety.')
print('The default parameters are as follows: \n'
      'input file: spectrum.xlsx\n'
      'output file: spectrum.xlsx\n'
      'window size: 10\n'
      'polynomial order: 3')
response = input('Do you want to change the parameters? (Y/N): ')
y = ['y', 'Y', 'н', 'Н']
if response in y:
    input_file = input('Enter the input file path: ')
    output_file = input('Enter the output file path: ')
    window_size = int(input('Enter the window size (integer): '))
    poly_order = int(input('Enter the polynomial order (integer): '))

df_means = pd.read_excel(input_file, sheet_name='Means')  # load the means of reflectance spectra
df_means.index = df_means['Wavelength']
df_means.drop(df_means.columns[[0]], axis=1, inplace=True)
df_out = pd.DataFrame()  # make new data frame for output
df_out.index = df_means.index

for col in df_means.columns:
    spectrum = df_means[col].to_numpy()
    smoothed = savgol_filter(spectrum, window_size, poly_order)  # Apply the Savitsky-Golay filter
    df_out[col] = smoothed

# Print the smoothed values
if input_file == output_file:
    with pd.ExcelWriter(output_file, engine='openpyxl', mode='a') as writer:
        df_out.to_excel(writer, sheet_name='Means-SavGol', index=True)
else:
    with pd.ExcelWriter(output_file, engine='openpyxl', mode='w') as writer:
        df_out.to_excel(writer, sheet_name='Means-SavGol', index=True)

print('Done!')

